name: Run Crypto Scraper

on:
  schedule:
    - cron: "*/30 * * * *"  # runs every 30 minutes
  workflow_dispatch:  # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: "crypto_news_scraper/0.1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scraper/crypto_news_scraper.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          git commit -m "Update scraped crypto news" || echo "No changes to commit"
          git push
